apiVersion: v1
kind: Pod
metadata:
  name: roadsterpod
  labels:
    name: roadsterpod2
spec:
  containers:
    - name: roadsterpod
      image: raghravi94/roadster:1.0
      ports:
        - name: tomcatport
          containerPort: 8080
          protocol: TCP
      readinessProbe:
        httpGet:
          path: /roadster/actuator/health/readiness
          port: 8080
        initialDelaySeconds: 5
        periodSeconds: 10
        failureThreshold: 3
      livenessProbe:
        httpGet:
          path: /roadster/actuator/health/liveness
          port: 8080
        initialDelaySeconds: 5
        periodSeconds: 10
        failureThreshold: 3